In [ ]:
"""
(7) Classificação Multiclasse com Naive Bayes

Utilize o Naive Bayes para realizar classificação multiclasse no conjunto de dados Iris.
Avalie o desempenho utilizando a precisão média ponderada (weighted precision) e a
matriz de confusão.
__________________________________________________________________________________________

(7) Multiclass Classification with Naive Bayes

Use Naive Bayes to perform multiclass classification on the Iris dataset.
Evaluate the performance using weighted precision and the confusion matrix.

"""

In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score

In [ ]:
# Loading the dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names) # This only gets the study features

# Loading the classification column
iris_df['target'] = iris.target

# Printing info about the dataset
print(iris_df)
print("\n")
print(iris_df.info())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                  5.1               3.5                1.4               0.2       0
1                  4.9               3.0                1.4               0.2       0
2                  4.7               3.2                1.3               0.2       0
3                  4.6               3.1                1.5               0.2       0
4                  5.0               3.6                1.4               0.2       0
..                 ...               ...                ...               ...     ...
145                6.7               3.0                5.2               2.3       2
146                6.3               2.5                5.0               1.9       2
147                6.5               3.0                5.2               2.0       2
148                6.2               3.4                5.4               2.3       2
149                5.9               3.0              

In [ ]:
# Defining the columns that are studied to make the classification
x = np.array(iris_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']])

# Defining the classification column
y = np.array(iris_df[['target']])

# Splitting the data into the training(70%) and validation(30%) sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)
print("{0:0.2f}% in the training set".format((len(x_train)/len(iris_df.index)) * 100))
print("{0:0.2f}% in the testing set".format((len(x_test)/len(iris_df.index)) * 100))

70.00% in the training set
30.00% in the testing set


In [ ]:
model = GaussianNB()
model.fit(x_train, y_train.ravel())

GaussianNB()

In [ ]:
# Predicting
y_pred = model.predict(x_test)

In [ ]:
# MEASURING MODEL WEIGHTED PRECISION
print("MODEL WEIGHTED PRECISION SCORE:")
precision_score(y_test, y_pred, average='weighted')

MODEL WEIGHTED PRECISION SCORE:


0.943859649122807

In [ ]:
model_conf_matrix = confusion_matrix(y_test, y_pred)
print("MODEL CONFUSION MATRIX:")
print(model_conf_matrix)

MODEL CONFUSION MATRIX:
[[12  0  0]
 [ 0 16  0]
 [ 0  3 14]]


In [ ]:
model_accuracy_score = accuracy_score(y_test, y_pred)
print(f"MODEL ACCURACY SCORE: {model_accuracy_score:.2f}")

MODEL ACCURACY SCORE: 0.93
